#############################################
# Based on DO Community Playbooks (Docker)
# Tested on Ubuntu 20.04.1 LTS
#############################################
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools', 'nginx', 'certbot', 'python3-certbot-nginx']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull mariadb Docker image
      docker_image:
        name: "{{ mariadb_container_image }}"
        source: pull

    # Create mariadb docker container
    - name: Create mariadb container
      docker_container:
        name: "{{ mariadb_container_name }}"
        image: "{{ mariadb_container_image }}"
        state: started
        networks:
            - name: skill-tracker
        env:
            MYSQL_ROOT_PASSWORD: "{{ lookup('file', './MARIADB_ROOT_PASSWORD.txt') }}"

    - name: Setup nginx configuration
      template:
        src=nginx/nginx.conf
        dest=/etc/nginx/nginx.conf
    - name: Setup nginx docker registry vhost
      template:
        src=nginx/registry.benrowland.net
        dest=/etc/nginx/sites-available/registry.benrowland.net
    - name: Setup nginx skill tracker app vhost
      template:
        src=nginx/st.benrowland.net
        dest=/etc/nginx/sites-available/st.benrowland.net
    - name: Setup nginx vhost for upcoming 443 mapping to tomcat backend (initially default page running on 443 to avoid port 80 getting started up)
      template:
        src=nginx/default
        dest=/etc/nginx/sites-available/default
    - name: Delete symlink for default site configuration
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent
    - name: Create sym link for docker registry vhost
      file:
        src: "/etc/nginx/sites-available/registry.benrowland.net"
        dest: "/etc/nginx/sites-enabled/registry.benrowland.net"
        state: link
    - name: Create sym link for skill tracker app vhost
      file:
        src: "/etc/nginx/sites-available/st.benrowland.net"
        dest: "/etc/nginx/sites-enabled/st.benrowland.net"
        state: link

    - name: Setup firewall with ufw
      ufw:
        rule: allow
        port: 22,80,443,5000
        proto: tcp

  handlers:
    - name: restart nginx
      service:
        name=nginx
        state=restarted
